global_costmap:
    publish_voxel_map: false
    global_frame: world
    robot_base_frame: base_link
    update_frequency: 2
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 30
    height: 30
